### ISSUE TITLE
0719-2문제 [자율]

### ISSUE THREAD

**Issue by clgusdl2** [clgusdl2/Alcorithm-study#57]
[자율] 스위치 켜고 끄기 1244번 실버4  [구현,시뮬레이션]
[자율] 트럭 13335번                               [시뮬레이션,Queue]

* 트럭 문제인 경우
* Queue 자료구조를 먼저 공부하시고 구현연습 진행 해주시면 됩니다.
* 트럭 같은 경우 예전 카카오였나 네이버였나.. 비슷한 문제 출제된 기억이?
*

**Comment by chcccccc** [comment]
넹
